apiVersion: v2
name: clearml-serving
description: ClearML Serving Helm Chart
type: application
version: "1.7.0"
appVersion: "1.3.0"
kubeVersion: ">= 1.21.0-0"
home: https://clear.ml
icon: https://raw.githubusercontent.com/clearml/clearml/master/docs/clearml-logo.svg
sources:
  - https://github.com/clearml/clearml-helm-charts
  - https://github.com/clearml/clearml
maintainers:
  - name: filippo-clearml
    url: https://github.com/filippo-clearml
keywords:
  - clearml
  - "machine learning"
  - mlops
  - "model serving"
dependencies:
  - name: kafka
    version: "21.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: prometheus
    version: "19.7.2"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "6.52.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Support for providing Clearml API credentials via secret"
