{{- if ( and .Values.clearml.createApiKeysSecret .Values.clearml.apiKeysSecretName ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clearml.apiKeysSecretName }}
type: Opaque
stringData:
  CLEARML_API_ACCESS_KEY: {{ .Values.clearml.apiAccessKey }}
  CLEARML_API_SECRET_KEY: {{ .Values.clearml.apiSecretKey }}
{{- end }}
